# Generated by Django 4.2.6 on 2023-11-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postingtag',
            name='unique_tag_post',
        ),
    ]
