# Generated by Django 4.2.6 on 2023-11-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_remove_postingtag_unique_tag_post'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postingtag',
            constraint=models.UniqueConstraint(fields=('posting', 'tag'), name='unique_tag_post'),
        ),
    ]
